In [1]:
import torch

In [24]:
x = torch.nn.Parameter(torch.rand(100, requires_grad=True))
x

Parameter containing:
tensor([0.5956, 0.3648, 0.3186, 0.9966, 0.3703, 0.2377, 0.6515, 0.4781, 0.2666,
        0.2021, 0.4316, 0.7793, 0.5155, 0.2032, 0.4882, 0.1496, 0.2735, 0.7793,
        0.5795, 0.3783, 0.0476, 0.2949, 0.5600, 0.5452, 0.0535, 0.4157, 0.2332,
        0.2836, 0.9630, 0.6195, 0.2034, 0.7572, 0.8557, 0.7176, 0.4382, 0.1881,
        0.0866, 0.5243, 0.2365, 0.7865, 0.4423, 0.7046, 0.2454, 0.9491, 0.7263,
        0.9066, 0.3920, 0.9584, 0.2857, 0.0331, 0.8630, 0.6776, 0.8900, 0.1761,
        0.8714, 0.3452, 0.5360, 0.7653, 0.1153, 0.1638, 0.7554, 0.9915, 0.5168,
        0.0537, 0.4590, 0.6063, 0.8849, 0.5401, 0.8708, 0.4792, 0.3134, 0.0854,
        0.8715, 0.4330, 0.0493, 0.0249, 0.6979, 0.1509, 0.0325, 0.0490, 0.5968,
        0.2431, 0.1177, 0.1362, 0.6316, 0.1862, 0.8323, 0.5836, 0.0103, 0.0957,
        0.8001, 0.9458, 0.8872, 0.4927, 0.5315, 0.5528, 0.7426, 0.3400, 0.5119,
        0.5877], requires_grad=True)

In [25]:
y = torch.topk(x, 10).values
y = y.sum()
y.backward()
x.grad

tensor([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 1., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
z = x[torch.topk(x, 10).indices]
z = z.sum()
z.backward
x.grad

tensor([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 1., 0., 0., 0., 0., 0., 0., 0.])